name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: default_db   # No importa, luego creamos las que queremos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    strategy:
      matrix:
        node-version: [22.x]
        service: [GestionSorteos, ManejoUsuarios]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./${{ matrix.service }}/package-lock.json

    - name: Install Dependencies
      run: npm ci
      working-directory: ./${{ matrix.service }}

    - name: Run Sequelize Drop Database
      run: npx sequelize-cli db:drop --env test
      working-directory: ./${{ matrix.service }}

    - name: Run Sequelize Create Database
      run: npx sequelize-cli db:create --env test
      working-directory: ./${{ matrix.service }}

    - name: Run Sequelize Migrations
      run: npx sequelize-cli db:migrate --env test
      working-directory: ./${{ matrix.service }}

    # 🟥 TESTS
    - name: Run Tests
      run: npm test
      working-directory: ./${{ matrix.service }}
