# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # 1. Nuevo bloque 'services' para la base de datos
    services:
        mysql:
          image: mysql:8.0 # Utiliza la imagen oficial de MySQL
          env:
              # Configura las variables de entorno para que coincidan con tu 'config.json' (entorno 'test')
              MYSQL_ROOT_PASSWORD: root # Coincide con el 'password' en config.json -> test
              MYSQL_DATABASE: std_gestionsorteos_db # Coincide con 'database' en config.json -> test
          ports:
              - 3306:3306
          options: >-
              --health-cmd="mysqladmin ping"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=10

    strategy:
      matrix:
        node-version: [22.x]
        service: [GestionSorteos, ManejoUsuarios]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./${{ matrix.service }}/package-lock.json

    - name: Install Dependencies
      run: npm ci
      working-directory: ./${{ matrix.service }}

    # Nuevo Paso: Ejecutar Drop de la Base de Datos
    - name: Run Sequelize Drop Database
      run: npx sequelize-cli db:drop 
      working-directory: ./${{ matrix.service }}

    # Nuevo Paso: Ejecutar Creación de la Base de Datos
    - name: Run Sequelize Create Database
      run: npx sequelize-cli db:create 
      working-directory: ./${{ matrix.service }}

    # Nuevo Paso: Ejecutar Migraciones de Base de Datos
    - name: Run Sequelize Migrations
      run: npx sequelize-cli db:migrate 
      working-directory: ./${{ matrix.service }}

      # Asegúrate de que este comando utilice la configuración de la BDD para 'test'
    - name: Run Tests
      run: npm test
      working-directory: ./${{ matrix.service }}
